---
services:
  samba:
    restart: always
    image: larstobi/samba:2025-12-28
    environment:
      TZ: "Europe/Oslo"
      GLOBAL: "hosts allow = 192.168. 10.0.0. 127. 172.16.0.6"
      GLOBAL1: "load printers = no"
      GLOBAL2: "security = user"
      GLOBAL3: "interfaces = 0.0.0.0/0"
      GLOBAL4: "idmap config * : range          = 1000000-1999999"
      RECYCLE: "false"
      WORKGROUP: "WORKGROUP"
      NMBD: "true"
      PERMISSIONS: "true"

      USERID: "1000"
      GROUPID: "1000"

      USER: "user1;changeme;2001"
      USER2: "user2;changeme;2002"
      USER3: "user3;changeme;2003"

      SHARE: "NAS;/mnt/nas;yes;no;no;user1 user3;'none';'none';'My Server Network Attached Storage"
      SHARE2: "Media;/mnt/media;yes;no;no;user1 user3 user2;'none';'none';'My Server Media"
      SHARE3: "Home;/mnt/home;yes;no;no;user1 user3 user2;'none';'none';'My Server Home"

    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    tmpfs:
      - /tmp
    stdin_open: true
    tty: true
    volumes:
      - /mnt:/mnt:z
    network_mode: host
